import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SignedOut>
          <section className="h-screen w-screen flex items-center justify-center gap-10 ">
            <div className="p-3 border-2 border-solid border-black rounded-3xl bg-green-400">
            <SignInButton />
            </div>
            <SignUpButton>
              <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer border-2 border-solid border-black">
                Sign Up
              </button>
            </SignUpButton>
          </section>
          </SignedOut>
          <SignedIn>
            {/* <UserButton/> */}
            {children}
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
